// Code generated by sequencegenerator; DO NOT EDIT.

package input


import (
    "github.com/guillermo/reacty/terminal/events"
)
type seq struct{
    seq   string
    event events.Event
}

var sequences = []seq{

    // ASCII Chars
    {"!", events.KeyboardEvent{Code: "!",Key: "!"}}, // !
    {"\"", events.KeyboardEvent{Code: "\"",Key: "\""}}, // "
    {"#", events.KeyboardEvent{Code: "#",Key: "#"}}, // #
    {"$", events.KeyboardEvent{Code: "$",Key: "$"}}, // $
    {"%", events.KeyboardEvent{Code: "%",Key: "%"}}, // %
    {"&", events.KeyboardEvent{Code: "&",Key: "&"}}, // &
    {"'", events.KeyboardEvent{Code: "'",Key: "'"}}, // '
    {"(", events.KeyboardEvent{Code: "(",Key: "("}}, // (
    {")", events.KeyboardEvent{Code: ")",Key: ")"}}, // )
    {"*", events.KeyboardEvent{Code: "*",Key: "*"}}, // *
    {"+", events.KeyboardEvent{Code: "+",Key: "+"}}, // +
    {",", events.KeyboardEvent{Code: ",",Key: ","}}, // ,
    {"-", events.KeyboardEvent{Code: "-",Key: "-"}}, // -
    {".", events.KeyboardEvent{Code: ".",Key: "."}}, // .
    {"/", events.KeyboardEvent{Code: "/",Key: "/"}}, // /
    {"0", events.KeyboardEvent{Code: "0",Key: "0"}}, // 0
    {"1", events.KeyboardEvent{Code: "1",Key: "1"}}, // 1
    {"2", events.KeyboardEvent{Code: "2",Key: "2"}}, // 2
    {"3", events.KeyboardEvent{Code: "3",Key: "3"}}, // 3
    {"4", events.KeyboardEvent{Code: "4",Key: "4"}}, // 4
    {"5", events.KeyboardEvent{Code: "5",Key: "5"}}, // 5
    {"6", events.KeyboardEvent{Code: "6",Key: "6"}}, // 6
    {"7", events.KeyboardEvent{Code: "7",Key: "7"}}, // 7
    {"8", events.KeyboardEvent{Code: "8",Key: "8"}}, // 8
    {"9", events.KeyboardEvent{Code: "9",Key: "9"}}, // 9
    {":", events.KeyboardEvent{Code: ":",Key: ":"}}, // :
    {";", events.KeyboardEvent{Code: ";",Key: ";"}}, // ;
    {"<", events.KeyboardEvent{Code: "<",Key: "<"}}, // <
    {"=", events.KeyboardEvent{Code: "=",Key: "="}}, // =
    {">", events.KeyboardEvent{Code: ">",Key: ">"}}, // >
    {"?", events.KeyboardEvent{Code: "?",Key: "?"}}, // ?
    {"@", events.KeyboardEvent{Code: "@",Key: "@"}}, // @
    {"A", events.KeyboardEvent{Code: "A",Key: "A"}}, // A
    {"B", events.KeyboardEvent{Code: "B",Key: "B"}}, // B
    {"C", events.KeyboardEvent{Code: "C",Key: "C"}}, // C
    {"D", events.KeyboardEvent{Code: "D",Key: "D"}}, // D
    {"E", events.KeyboardEvent{Code: "E",Key: "E"}}, // E
    {"F", events.KeyboardEvent{Code: "F",Key: "F"}}, // F
    {"G", events.KeyboardEvent{Code: "G",Key: "G"}}, // G
    {"H", events.KeyboardEvent{Code: "H",Key: "H"}}, // H
    {"I", events.KeyboardEvent{Code: "I",Key: "I"}}, // I
    {"J", events.KeyboardEvent{Code: "J",Key: "J"}}, // J
    {"K", events.KeyboardEvent{Code: "K",Key: "K"}}, // K
    {"L", events.KeyboardEvent{Code: "L",Key: "L"}}, // L
    {"M", events.KeyboardEvent{Code: "M",Key: "M"}}, // M
    {"N", events.KeyboardEvent{Code: "N",Key: "N"}}, // N
    {"O", events.KeyboardEvent{Code: "O",Key: "O"}}, // O
    {"P", events.KeyboardEvent{Code: "P",Key: "P"}}, // P
    {"Q", events.KeyboardEvent{Code: "Q",Key: "Q"}}, // Q
    {"R", events.KeyboardEvent{Code: "R",Key: "R"}}, // R
    {"S", events.KeyboardEvent{Code: "S",Key: "S"}}, // S
    {"T", events.KeyboardEvent{Code: "T",Key: "T"}}, // T
    {"U", events.KeyboardEvent{Code: "U",Key: "U"}}, // U
    {"V", events.KeyboardEvent{Code: "V",Key: "V"}}, // V
    {"W", events.KeyboardEvent{Code: "W",Key: "W"}}, // W
    {"X", events.KeyboardEvent{Code: "X",Key: "X"}}, // X
    {"Y", events.KeyboardEvent{Code: "Y",Key: "Y"}}, // Y
    {"Z", events.KeyboardEvent{Code: "Z",Key: "Z"}}, // Z
    {"[", events.KeyboardEvent{Code: "[",Key: "["}}, // [
    {"\\", events.KeyboardEvent{Code: "\\",Key: "\\"}}, // \
    {"]", events.KeyboardEvent{Code: "]",Key: "]"}}, // ]
    {"^", events.KeyboardEvent{Code: "^",Key: "^"}}, // ^
    {"_", events.KeyboardEvent{Code: "_",Key: "_"}}, // _
    {"`", events.KeyboardEvent{Code: "`",Key: "`"}}, // `
    {"a", events.KeyboardEvent{Code: "a",Key: "a"}}, // a
    {"b", events.KeyboardEvent{Code: "b",Key: "b"}}, // b
    {"c", events.KeyboardEvent{Code: "c",Key: "c"}}, // c
    {"d", events.KeyboardEvent{Code: "d",Key: "d"}}, // d
    {"e", events.KeyboardEvent{Code: "e",Key: "e"}}, // e
    {"f", events.KeyboardEvent{Code: "f",Key: "f"}}, // f
    {"g", events.KeyboardEvent{Code: "g",Key: "g"}}, // g
    {"h", events.KeyboardEvent{Code: "h",Key: "h"}}, // h
    {"i", events.KeyboardEvent{Code: "i",Key: "i"}}, // i
    {"j", events.KeyboardEvent{Code: "j",Key: "j"}}, // j
    {"k", events.KeyboardEvent{Code: "k",Key: "k"}}, // k
    {"l", events.KeyboardEvent{Code: "l",Key: "l"}}, // l
    {"m", events.KeyboardEvent{Code: "m",Key: "m"}}, // m
    {"n", events.KeyboardEvent{Code: "n",Key: "n"}}, // n
    {"o", events.KeyboardEvent{Code: "o",Key: "o"}}, // o
    {"p", events.KeyboardEvent{Code: "p",Key: "p"}}, // p
    {"q", events.KeyboardEvent{Code: "q",Key: "q"}}, // q
    {"r", events.KeyboardEvent{Code: "r",Key: "r"}}, // r
    {"s", events.KeyboardEvent{Code: "s",Key: "s"}}, // s
    {"t", events.KeyboardEvent{Code: "t",Key: "t"}}, // t
    {"u", events.KeyboardEvent{Code: "u",Key: "u"}}, // u
    {"v", events.KeyboardEvent{Code: "v",Key: "v"}}, // v
    {"w", events.KeyboardEvent{Code: "w",Key: "w"}}, // w
    {"x", events.KeyboardEvent{Code: "x",Key: "x"}}, // x
    {"y", events.KeyboardEvent{Code: "y",Key: "y"}}, // y
    {"z", events.KeyboardEvent{Code: "z",Key: "z"}}, // z
    {"{", events.KeyboardEvent{Code: "{",Key: "{"}}, // {
    {"|", events.KeyboardEvent{Code: "|",Key: "|"}}, // |
    {"}", events.KeyboardEvent{Code: "}",Key: "}"}}, // }
    {"~", events.KeyboardEvent{Code: "~",Key: "~"}}, // ~

    // Control Keys
    {"\x01", events.KeyboardEvent{Code: "A", Ctrl: true}}, // Ctrl+A
    {"\x02", events.KeyboardEvent{Code: "B", Ctrl: true}}, // Ctrl+B
    {"\x03", events.KeyboardEvent{Code: "C", Ctrl: true}}, // Ctrl+C
    {"\x04", events.KeyboardEvent{Code: "D", Ctrl: true}}, // Ctrl+D
    {"\x05", events.KeyboardEvent{Code: "E", Ctrl: true}}, // Ctrl+E
    {"\x06", events.KeyboardEvent{Code: "F", Ctrl: true}}, // Ctrl+F
    {"\a", events.KeyboardEvent{Code: "G", Ctrl: true}}, // Ctrl+G
    {"\b", events.KeyboardEvent{Code: "H", Ctrl: true}}, // Ctrl+H
    {"\t", events.KeyboardEvent{Code: "I", Ctrl: true}}, // Ctrl+I
    {"\n", events.KeyboardEvent{Code: "J", Ctrl: true}}, // Ctrl+J
    {"\v", events.KeyboardEvent{Code: "K", Ctrl: true}}, // Ctrl+K
    {"\f", events.KeyboardEvent{Code: "L", Ctrl: true}}, // Ctrl+L
    {"\r", events.KeyboardEvent{Code: "M", Ctrl: true}}, // Ctrl+M
    {"\x0e", events.KeyboardEvent{Code: "N", Ctrl: true}}, // Ctrl+N
    {"\x0f", events.KeyboardEvent{Code: "O", Ctrl: true}}, // Ctrl+O
    {"\x10", events.KeyboardEvent{Code: "P", Ctrl: true}}, // Ctrl+P
    {"\x11", events.KeyboardEvent{Code: "Q", Ctrl: true}}, // Ctrl+Q
    {"\x12", events.KeyboardEvent{Code: "R", Ctrl: true}}, // Ctrl+R
    {"\x13", events.KeyboardEvent{Code: "S", Ctrl: true}}, // Ctrl+S
    {"\x14", events.KeyboardEvent{Code: "T", Ctrl: true}}, // Ctrl+T
    {"\x15", events.KeyboardEvent{Code: "U", Ctrl: true}}, // Ctrl+U
    {"\x16", events.KeyboardEvent{Code: "V", Ctrl: true}}, // Ctrl+V
    {"\x17", events.KeyboardEvent{Code: "W", Ctrl: true}}, // Ctrl+W
    {"\x18", events.KeyboardEvent{Code: "X", Ctrl: true}}, // Ctrl+X
    {"\x19", events.KeyboardEvent{Code: "Y", Ctrl: true}}, // Ctrl+Y
    {"\x1a", events.KeyboardEvent{Code: "Z", Ctrl: true}}, // Ctrl+Z

    // Alt Keys
    {"\x1b!", events.KeyboardEvent{Code: "!", Alt: true}}, // Alt+!
    {"\x1b\"", events.KeyboardEvent{Code: "\"", Alt: true}}, // Alt+"
    {"\x1b#", events.KeyboardEvent{Code: "#", Alt: true}}, // Alt+#
    {"\x1b$", events.KeyboardEvent{Code: "$", Alt: true}}, // Alt+$
    {"\x1b%", events.KeyboardEvent{Code: "%", Alt: true}}, // Alt+%
    {"\x1b&", events.KeyboardEvent{Code: "&", Alt: true}}, // Alt+&
    {"\x1b'", events.KeyboardEvent{Code: "'", Alt: true}}, // Alt+'
    {"\x1b(", events.KeyboardEvent{Code: "(", Alt: true}}, // Alt+(
    {"\x1b)", events.KeyboardEvent{Code: ")", Alt: true}}, // Alt+)
    {"\x1b*", events.KeyboardEvent{Code: "*", Alt: true}}, // Alt+*
    {"\x1b+", events.KeyboardEvent{Code: "+", Alt: true}}, // Alt++
    {"\x1b,", events.KeyboardEvent{Code: ",", Alt: true}}, // Alt+,
    {"\x1b-", events.KeyboardEvent{Code: "-", Alt: true}}, // Alt+-
    {"\x1b.", events.KeyboardEvent{Code: ".", Alt: true}}, // Alt+.
    {"\x1b/", events.KeyboardEvent{Code: "/", Alt: true}}, // Alt+/
    {"\x1b0", events.KeyboardEvent{Code: "0", Alt: true}}, // Alt+0
    {"\x1b1", events.KeyboardEvent{Code: "1", Alt: true}}, // Alt+1
    {"\x1b2", events.KeyboardEvent{Code: "2", Alt: true}}, // Alt+2
    {"\x1b3", events.KeyboardEvent{Code: "3", Alt: true}}, // Alt+3
    {"\x1b4", events.KeyboardEvent{Code: "4", Alt: true}}, // Alt+4
    {"\x1b5", events.KeyboardEvent{Code: "5", Alt: true}}, // Alt+5
    {"\x1b6", events.KeyboardEvent{Code: "6", Alt: true}}, // Alt+6
    {"\x1b7", events.KeyboardEvent{Code: "7", Alt: true}}, // Alt+7
    {"\x1b8", events.KeyboardEvent{Code: "8", Alt: true}}, // Alt+8
    {"\x1b9", events.KeyboardEvent{Code: "9", Alt: true}}, // Alt+9
    {"\x1b:", events.KeyboardEvent{Code: ":", Alt: true}}, // Alt+:
    {"\x1b;", events.KeyboardEvent{Code: ";", Alt: true}}, // Alt+;
    {"\x1b<", events.KeyboardEvent{Code: "<", Alt: true}}, // Alt+<
    {"\x1b=", events.KeyboardEvent{Code: "=", Alt: true}}, // Alt+=
    {"\x1b>", events.KeyboardEvent{Code: ">", Alt: true}}, // Alt+>
    {"\x1b?", events.KeyboardEvent{Code: "?", Alt: true}}, // Alt+?
    {"\x1b@", events.KeyboardEvent{Code: "@", Alt: true}}, // Alt+@
    {"\x1bA", events.KeyboardEvent{Code: "A", Alt: true}}, // Alt+A
    {"\x1bB", events.KeyboardEvent{Code: "B", Alt: true}}, // Alt+B
    {"\x1bC", events.KeyboardEvent{Code: "C", Alt: true}}, // Alt+C
    {"\x1bD", events.KeyboardEvent{Code: "D", Alt: true}}, // Alt+D
    {"\x1bE", events.KeyboardEvent{Code: "E", Alt: true}}, // Alt+E
    {"\x1bF", events.KeyboardEvent{Code: "F", Alt: true}}, // Alt+F
    {"\x1bG", events.KeyboardEvent{Code: "G", Alt: true}}, // Alt+G
    {"\x1bH", events.KeyboardEvent{Code: "H", Alt: true}}, // Alt+H
    {"\x1bI", events.KeyboardEvent{Code: "I", Alt: true}}, // Alt+I
    {"\x1bJ", events.KeyboardEvent{Code: "J", Alt: true}}, // Alt+J
    {"\x1bK", events.KeyboardEvent{Code: "K", Alt: true}}, // Alt+K
    {"\x1bL", events.KeyboardEvent{Code: "L", Alt: true}}, // Alt+L
    {"\x1bM", events.KeyboardEvent{Code: "M", Alt: true}}, // Alt+M
    {"\x1bN", events.KeyboardEvent{Code: "N", Alt: true}}, // Alt+N
    {"\x1bO", events.KeyboardEvent{Code: "O", Alt: true}}, // Alt+O
    {"\x1bP", events.KeyboardEvent{Code: "P", Alt: true}}, // Alt+P
    {"\x1bQ", events.KeyboardEvent{Code: "Q", Alt: true}}, // Alt+Q
    {"\x1bR", events.KeyboardEvent{Code: "R", Alt: true}}, // Alt+R
    {"\x1bS", events.KeyboardEvent{Code: "S", Alt: true}}, // Alt+S
    {"\x1bT", events.KeyboardEvent{Code: "T", Alt: true}}, // Alt+T
    {"\x1bU", events.KeyboardEvent{Code: "U", Alt: true}}, // Alt+U
    {"\x1bV", events.KeyboardEvent{Code: "V", Alt: true}}, // Alt+V
    {"\x1bW", events.KeyboardEvent{Code: "W", Alt: true}}, // Alt+W
    {"\x1bX", events.KeyboardEvent{Code: "X", Alt: true}}, // Alt+X
    {"\x1bY", events.KeyboardEvent{Code: "Y", Alt: true}}, // Alt+Y
    {"\x1bZ", events.KeyboardEvent{Code: "Z", Alt: true}}, // Alt+Z
    {"\x1b[", events.KeyboardEvent{Code: "[", Alt: true}}, // Alt+[
    {"\x1b\\", events.KeyboardEvent{Code: "\\", Alt: true}}, // Alt+\
    {"\x1b]", events.KeyboardEvent{Code: "]", Alt: true}}, // Alt+]
    {"\x1b^", events.KeyboardEvent{Code: "^", Alt: true}}, // Alt+^
    {"\x1b_", events.KeyboardEvent{Code: "_", Alt: true}}, // Alt+_
    {"\x1b`", events.KeyboardEvent{Code: "`", Alt: true}}, // Alt+`
    {"\x1ba", events.KeyboardEvent{Code: "a", Alt: true}}, // Alt+a
    {"\x1bb", events.KeyboardEvent{Code: "b", Alt: true}}, // Alt+b
    {"\x1bc", events.KeyboardEvent{Code: "c", Alt: true}}, // Alt+c
    {"\x1bd", events.KeyboardEvent{Code: "d", Alt: true}}, // Alt+d
    {"\x1be", events.KeyboardEvent{Code: "e", Alt: true}}, // Alt+e
    {"\x1bf", events.KeyboardEvent{Code: "f", Alt: true}}, // Alt+f
    {"\x1bg", events.KeyboardEvent{Code: "g", Alt: true}}, // Alt+g
    {"\x1bh", events.KeyboardEvent{Code: "h", Alt: true}}, // Alt+h
    {"\x1bi", events.KeyboardEvent{Code: "i", Alt: true}}, // Alt+i
    {"\x1bj", events.KeyboardEvent{Code: "j", Alt: true}}, // Alt+j
    {"\x1bk", events.KeyboardEvent{Code: "k", Alt: true}}, // Alt+k
    {"\x1bl", events.KeyboardEvent{Code: "l", Alt: true}}, // Alt+l
    {"\x1bm", events.KeyboardEvent{Code: "m", Alt: true}}, // Alt+m
    {"\x1bn", events.KeyboardEvent{Code: "n", Alt: true}}, // Alt+n
    {"\x1bo", events.KeyboardEvent{Code: "o", Alt: true}}, // Alt+o
    {"\x1bp", events.KeyboardEvent{Code: "p", Alt: true}}, // Alt+p
    {"\x1bq", events.KeyboardEvent{Code: "q", Alt: true}}, // Alt+q
    {"\x1br", events.KeyboardEvent{Code: "r", Alt: true}}, // Alt+r
    {"\x1bs", events.KeyboardEvent{Code: "s", Alt: true}}, // Alt+s
    {"\x1bt", events.KeyboardEvent{Code: "t", Alt: true}}, // Alt+t
    {"\x1bu", events.KeyboardEvent{Code: "u", Alt: true}}, // Alt+u
    {"\x1bv", events.KeyboardEvent{Code: "v", Alt: true}}, // Alt+v
    {"\x1bw", events.KeyboardEvent{Code: "w", Alt: true}}, // Alt+w
    {"\x1bx", events.KeyboardEvent{Code: "x", Alt: true}}, // Alt+x
    {"\x1by", events.KeyboardEvent{Code: "y", Alt: true}}, // Alt+y
    {"\x1bz", events.KeyboardEvent{Code: "z", Alt: true}}, // Alt+z
    {"\x1b{", events.KeyboardEvent{Code: "{", Alt: true}}, // Alt+{
    {"\x1b|", events.KeyboardEvent{Code: "|", Alt: true}}, // Alt+|
    {"\x1b}", events.KeyboardEvent{Code: "}", Alt: true}}, // Alt+}
    {"\x1b~", events.KeyboardEvent{Code: "~", Alt: true}}, // Alt+~

    // Control + Alt Keys
    {"\x1b\x01", events.KeyboardEvent{Code: "A", Alt: true, Ctrl: true}}, // Ctrl+Alt+A
    {"\x1b\x02", events.KeyboardEvent{Code: "B", Alt: true, Ctrl: true}}, // Ctrl+Alt+B
    {"\x1b\x03", events.KeyboardEvent{Code: "C", Alt: true, Ctrl: true}}, // Ctrl+Alt+C
    {"\x1b\x04", events.KeyboardEvent{Code: "D", Alt: true, Ctrl: true}}, // Ctrl+Alt+D
    {"\x1b\x05", events.KeyboardEvent{Code: "E", Alt: true, Ctrl: true}}, // Ctrl+Alt+E
    {"\x1b\x06", events.KeyboardEvent{Code: "F", Alt: true, Ctrl: true}}, // Ctrl+Alt+F
    {"\x1b\a", events.KeyboardEvent{Code: "G", Alt: true, Ctrl: true}}, // Ctrl+Alt+G
    {"\x1b\b", events.KeyboardEvent{Code: "H", Alt: true, Ctrl: true}}, // Ctrl+Alt+H
    {"\x1b\t", events.KeyboardEvent{Code: "I", Alt: true, Ctrl: true}}, // Ctrl+Alt+I
    {"\x1b\n", events.KeyboardEvent{Code: "J", Alt: true, Ctrl: true}}, // Ctrl+Alt+J
    {"\x1b\v", events.KeyboardEvent{Code: "K", Alt: true, Ctrl: true}}, // Ctrl+Alt+K
    {"\x1b\f", events.KeyboardEvent{Code: "L", Alt: true, Ctrl: true}}, // Ctrl+Alt+L
    {"\x1b\r", events.KeyboardEvent{Code: "M", Alt: true, Ctrl: true}}, // Ctrl+Alt+M
    {"\x1b\x0e", events.KeyboardEvent{Code: "N", Alt: true, Ctrl: true}}, // Ctrl+Alt+N
    {"\x1b\x0f", events.KeyboardEvent{Code: "O", Alt: true, Ctrl: true}}, // Ctrl+Alt+O
    {"\x1b\x10", events.KeyboardEvent{Code: "P", Alt: true, Ctrl: true}}, // Ctrl+Alt+P
    {"\x1b\x11", events.KeyboardEvent{Code: "Q", Alt: true, Ctrl: true}}, // Ctrl+Alt+Q
    {"\x1b\x12", events.KeyboardEvent{Code: "R", Alt: true, Ctrl: true}}, // Ctrl+Alt+R
    {"\x1b\x13", events.KeyboardEvent{Code: "S", Alt: true, Ctrl: true}}, // Ctrl+Alt+S
    {"\x1b\x14", events.KeyboardEvent{Code: "T", Alt: true, Ctrl: true}}, // Ctrl+Alt+T
    {"\x1b\x15", events.KeyboardEvent{Code: "U", Alt: true, Ctrl: true}}, // Ctrl+Alt+U
    {"\x1b\x16", events.KeyboardEvent{Code: "V", Alt: true, Ctrl: true}}, // Ctrl+Alt+V
    {"\x1b\x17", events.KeyboardEvent{Code: "W", Alt: true, Ctrl: true}}, // Ctrl+Alt+W
    {"\x1b\x18", events.KeyboardEvent{Code: "X", Alt: true, Ctrl: true}}, // Ctrl+Alt+X
    {"\x1b\x19", events.KeyboardEvent{Code: "Y", Alt: true, Ctrl: true}}, // Ctrl+Alt+Y
    {"\x1b\x1a", events.KeyboardEvent{Code: "Z", Alt: true, Ctrl: true}}, // Ctrl+Alt+Z

    // Fn and directions
    // Normal
    {"\x1bOP", events.KeyboardEvent{Code: "F1"}}, // F1
    {"\x1bOQ", events.KeyboardEvent{Code: "F2"}}, // F2
    {"\x1bOR", events.KeyboardEvent{Code: "F3"}}, // F3
    {"\x1bOS", events.KeyboardEvent{Code: "F4"}}, // F4
    {"\x1b[15~", events.KeyboardEvent{Code: "F5"}}, // F5
    {"\x1b[17~", events.KeyboardEvent{Code: "F6"}}, // F6
    {"\x1b[18~", events.KeyboardEvent{Code: "F7"}}, // F7
    {"\x1b[19~", events.KeyboardEvent{Code: "F8"}}, // F8
    {"\x1b[20~", events.KeyboardEvent{Code: "F9"}}, // F9
    {"\x1b[21~", events.KeyboardEvent{Code: "F10"}}, // F10
    {"\x1b[23~", events.KeyboardEvent{Code: "F11"}}, // F11
    {"\x1b[24~", events.KeyboardEvent{Code: "F12"}}, // F12
    {"\x1b[5~", events.KeyboardEvent{Code: "PageUp"}}, // PageUp
    {"\x1b[6~", events.KeyboardEvent{Code: "PageDown"}}, // PageDown
    {"\x1b[H", events.KeyboardEvent{Code: "Home"}}, // Home
    {"\x1b[F", events.KeyboardEvent{Code: "End"}}, // End
    {"\x1b[2~", events.KeyboardEvent{Code: "Insert"}}, // Insert
    {"\x1b[3~", events.KeyboardEvent{Code: "Delete"}}, // Delete
    {"\x1b[A", events.KeyboardEvent{Code: "Up"}}, // Up
    {"\x1b[B", events.KeyboardEvent{Code: "Down"}}, // Down
    {"\x1b[C", events.KeyboardEvent{Code: "Right"}}, // Right
    {"\x1b[D", events.KeyboardEvent{Code: "Left"}}, // Left
    // Ctrl
    {"\x1b[;5P", events.KeyboardEvent{Code: "F1", Ctrl: true}}, // Ctrl+F1
    {"\x1b[;5Q", events.KeyboardEvent{Code: "F2", Ctrl: true}}, // Ctrl+F2
    {"\x1b[;5R", events.KeyboardEvent{Code: "F3", Ctrl: true}}, // Ctrl+F3
    {"\x1b[;5S", events.KeyboardEvent{Code: "F4", Ctrl: true}}, // Ctrl+F4
    {"\x1b[15;5~", events.KeyboardEvent{Code: "F5", Ctrl: true}}, // Ctrl+F5
    {"\x1b[17;5~", events.KeyboardEvent{Code: "F6", Ctrl: true}}, // Ctrl+F6
    {"\x1b[18;5~", events.KeyboardEvent{Code: "F7", Ctrl: true}}, // Ctrl+F7
    {"\x1b[19;5~", events.KeyboardEvent{Code: "F8", Ctrl: true}}, // Ctrl+F8
    {"\x1b[20;5~", events.KeyboardEvent{Code: "F9", Ctrl: true}}, // Ctrl+F9
    {"\x1b[21;5~", events.KeyboardEvent{Code: "F10", Ctrl: true}}, // Ctrl+F10
    {"\x1b[23;5~", events.KeyboardEvent{Code: "F11", Ctrl: true}}, // Ctrl+F11
    {"\x1b[24;5~", events.KeyboardEvent{Code: "F12", Ctrl: true}}, // Ctrl+F12
    {"\x1b[5;5~", events.KeyboardEvent{Code: "PageUp", Ctrl: true}}, // Ctrl+PageUp
    {"\x1b[6;5~", events.KeyboardEvent{Code: "PageDown", Ctrl: true}}, // Ctrl+PageDown
    {"\x1b[1;5H", events.KeyboardEvent{Code: "Home", Ctrl: true}}, // Ctrl+Home
    {"\x1b[1;5F", events.KeyboardEvent{Code: "End", Ctrl: true}}, // Ctrl+End
    {"\x1b[2;5~", events.KeyboardEvent{Code: "Insert", Ctrl: true}}, // Ctrl+Insert
    {"\x1b[3;5~", events.KeyboardEvent{Code: "Delete", Ctrl: true}}, // Ctrl+Delete
    {"\x1b[1;5A", events.KeyboardEvent{Code: "Up", Ctrl: true}}, // Ctrl+Up
    {"\x1b[1;5B", events.KeyboardEvent{Code: "Down", Ctrl: true}}, // Ctrl+Down
    {"\x1b[1;5C", events.KeyboardEvent{Code: "Right", Ctrl: true}}, // Ctrl+Right
    {"\x1b[1;5D", events.KeyboardEvent{Code: "Left", Ctrl: true}}, // Ctrl+Left
    // Alt
    {"\x1b[;3P", events.KeyboardEvent{Code: "F1", Alt: true}}, // Alt+F1
    {"\x1b[;3Q", events.KeyboardEvent{Code: "F2", Alt: true}}, // Alt+F2
    {"\x1b[;3R", events.KeyboardEvent{Code: "F3", Alt: true}}, // Alt+F3
    {"\x1b[;3S", events.KeyboardEvent{Code: "F4", Alt: true}}, // Alt+F4
    {"\x1b[15;3~", events.KeyboardEvent{Code: "F5", Alt: true}}, // Alt+F5
    {"\x1b[17;3~", events.KeyboardEvent{Code: "F6", Alt: true}}, // Alt+F6
    {"\x1b[18;3~", events.KeyboardEvent{Code: "F7", Alt: true}}, // Alt+F7
    {"\x1b[19;3~", events.KeyboardEvent{Code: "F8", Alt: true}}, // Alt+F8
    {"\x1b[20;3~", events.KeyboardEvent{Code: "F9", Alt: true}}, // Alt+F9
    {"\x1b[21;3~", events.KeyboardEvent{Code: "F10", Alt: true}}, // Alt+F10
    {"\x1b[23;3~", events.KeyboardEvent{Code: "F11", Alt: true}}, // Alt+F11
    {"\x1b[24;3~", events.KeyboardEvent{Code: "F12", Alt: true}}, // Alt+F12
    {"\x1b[5;3~", events.KeyboardEvent{Code: "PageUp", Alt: true}}, // Alt+PageUp
    {"\x1b[6;3~", events.KeyboardEvent{Code: "PageDown", Alt: true}}, // Alt+PageDown
    {"\x1b[1;3H", events.KeyboardEvent{Code: "Home", Alt: true}}, // Alt+Home
    {"\x1b[1;3F", events.KeyboardEvent{Code: "End", Alt: true}}, // Alt+End
    {"\x1b[2;3~", events.KeyboardEvent{Code: "Insert", Alt: true}}, // Alt+Insert
    {"\x1b[3;3~", events.KeyboardEvent{Code: "Delete", Alt: true}}, // Alt+Delete
    {"\x1b[1;3A", events.KeyboardEvent{Code: "Up", Alt: true}}, // Alt+Up
    {"\x1b[1;3B", events.KeyboardEvent{Code: "Down", Alt: true}}, // Alt+Down
    {"\x1b[1;3C", events.KeyboardEvent{Code: "Right", Alt: true}}, // Alt+Right
    {"\x1b[1;3D", events.KeyboardEvent{Code: "Left", Alt: true}}, // Alt+Left
    // Shift
    {"\x1b[;2P", events.KeyboardEvent{Code: "F1", Shift: true}}, // Shift+F1
    {"\x1b[;2Q", events.KeyboardEvent{Code: "F2", Shift: true}}, // Shift+F2
    {"\x1b[;2R", events.KeyboardEvent{Code: "F3", Shift: true}}, // Shift+F3
    {"\x1b[;2S", events.KeyboardEvent{Code: "F4", Shift: true}}, // Shift+F4
    {"\x1b[15;2~", events.KeyboardEvent{Code: "F5", Shift: true}}, // Shift+F5
    {"\x1b[17;2~", events.KeyboardEvent{Code: "F6", Shift: true}}, // Shift+F6
    {"\x1b[18;2~", events.KeyboardEvent{Code: "F7", Shift: true}}, // Shift+F7
    {"\x1b[19;2~", events.KeyboardEvent{Code: "F8", Shift: true}}, // Shift+F8
    {"\x1b[20;2~", events.KeyboardEvent{Code: "F9", Shift: true}}, // Shift+F9
    {"\x1b[21;2~", events.KeyboardEvent{Code: "F10", Shift: true}}, // Shift+F10
    {"\x1b[23;2~", events.KeyboardEvent{Code: "F11", Shift: true}}, // Shift+F11
    {"\x1b[24;2~", events.KeyboardEvent{Code: "F12", Shift: true}}, // Shift+F12
    {"\x1b[5;2~", events.KeyboardEvent{Code: "PageUp", Shift: true}}, // Shift+PageUp
    {"\x1b[6;2~", events.KeyboardEvent{Code: "PageDown", Shift: true}}, // Shift+PageDown
    {"\x1b[1;2H", events.KeyboardEvent{Code: "Home", Shift: true}}, // Shift+Home
    {"\x1b[1;2F", events.KeyboardEvent{Code: "End", Shift: true}}, // Shift+End
    {"\x1b[2;2~", events.KeyboardEvent{Code: "Insert", Shift: true}}, // Shift+Insert
    {"\x1b[3;2~", events.KeyboardEvent{Code: "Delete", Shift: true}}, // Shift+Delete
    {"\x1b[1;2A", events.KeyboardEvent{Code: "Up", Shift: true}}, // Shift+Up
    {"\x1b[1;2B", events.KeyboardEvent{Code: "Down", Shift: true}}, // Shift+Down
    {"\x1b[1;2C", events.KeyboardEvent{Code: "Right", Shift: true}}, // Shift+Right
    {"\x1b[1;2D", events.KeyboardEvent{Code: "Left", Shift: true}}, // Shift+Left
    // Ctrl + Alt
    {"\x1b[;7P", events.KeyboardEvent{Code: "F1", Alt: true, Ctrl: true}}, // Ctrl+Alt+F1
    {"\x1b[;7Q", events.KeyboardEvent{Code: "F2", Alt: true, Ctrl: true}}, // Ctrl+Alt+F2
    {"\x1b[;7R", events.KeyboardEvent{Code: "F3", Alt: true, Ctrl: true}}, // Ctrl+Alt+F3
    {"\x1b[;7S", events.KeyboardEvent{Code: "F4", Alt: true, Ctrl: true}}, // Ctrl+Alt+F4
    {"\x1b[15;7~", events.KeyboardEvent{Code: "F5", Alt: true, Ctrl: true}}, // Ctrl+Alt+F5
    {"\x1b[17;7~", events.KeyboardEvent{Code: "F6", Alt: true, Ctrl: true}}, // Ctrl+Alt+F6
    {"\x1b[18;7~", events.KeyboardEvent{Code: "F7", Alt: true, Ctrl: true}}, // Ctrl+Alt+F7
    {"\x1b[19;7~", events.KeyboardEvent{Code: "F8", Alt: true, Ctrl: true}}, // Ctrl+Alt+F8
    {"\x1b[20;7~", events.KeyboardEvent{Code: "F9", Alt: true, Ctrl: true}}, // Ctrl+Alt+F9
    {"\x1b[21;7~", events.KeyboardEvent{Code: "F10", Alt: true, Ctrl: true}}, // Ctrl+Alt+F10
    {"\x1b[23;7~", events.KeyboardEvent{Code: "F11", Alt: true, Ctrl: true}}, // Ctrl+Alt+F11
    {"\x1b[24;7~", events.KeyboardEvent{Code: "F12", Alt: true, Ctrl: true}}, // Ctrl+Alt+F12
    {"\x1b[5;7~", events.KeyboardEvent{Code: "PageUp", Alt: true, Ctrl: true}}, // Ctrl+Alt+PageUp
    {"\x1b[6;7~", events.KeyboardEvent{Code: "PageDown", Alt: true, Ctrl: true}}, // Ctrl+Alt+PageDown
    {"\x1b[1;7H", events.KeyboardEvent{Code: "Home", Alt: true, Ctrl: true}}, // Ctrl+Alt+Home
    {"\x1b[1;7F", events.KeyboardEvent{Code: "End", Alt: true, Ctrl: true}}, // Ctrl+Alt+End
    {"\x1b[2;7~", events.KeyboardEvent{Code: "Insert", Alt: true, Ctrl: true}}, // Ctrl+Alt+Insert
    {"\x1b[3;7~", events.KeyboardEvent{Code: "Delete", Alt: true, Ctrl: true}}, // Ctrl+Alt+Delete
    {"\x1b[1;7A", events.KeyboardEvent{Code: "Up", Alt: true, Ctrl: true}}, // Ctrl+Alt+Up
    {"\x1b[1;7B", events.KeyboardEvent{Code: "Down", Alt: true, Ctrl: true}}, // Ctrl+Alt+Down
    {"\x1b[1;7C", events.KeyboardEvent{Code: "Right", Alt: true, Ctrl: true}}, // Ctrl+Alt+Right
    {"\x1b[1;7D", events.KeyboardEvent{Code: "Left", Alt: true, Ctrl: true}}, // Ctrl+Alt+Left
    // Ctrl + Shift
    {"\x1b[;6P", events.KeyboardEvent{Code: "F1", Ctrl: true, Shift: true}}, // Shift+Ctrl+F1
    {"\x1b[;6Q", events.KeyboardEvent{Code: "F2", Ctrl: true, Shift: true}}, // Shift+Ctrl+F2
    {"\x1b[;6R", events.KeyboardEvent{Code: "F3", Ctrl: true, Shift: true}}, // Shift+Ctrl+F3
    {"\x1b[;6S", events.KeyboardEvent{Code: "F4", Ctrl: true, Shift: true}}, // Shift+Ctrl+F4
    {"\x1b[15;6~", events.KeyboardEvent{Code: "F5", Ctrl: true, Shift: true}}, // Shift+Ctrl+F5
    {"\x1b[17;6~", events.KeyboardEvent{Code: "F6", Ctrl: true, Shift: true}}, // Shift+Ctrl+F6
    {"\x1b[18;6~", events.KeyboardEvent{Code: "F7", Ctrl: true, Shift: true}}, // Shift+Ctrl+F7
    {"\x1b[19;6~", events.KeyboardEvent{Code: "F8", Ctrl: true, Shift: true}}, // Shift+Ctrl+F8
    {"\x1b[20;6~", events.KeyboardEvent{Code: "F9", Ctrl: true, Shift: true}}, // Shift+Ctrl+F9
    {"\x1b[21;6~", events.KeyboardEvent{Code: "F10", Ctrl: true, Shift: true}}, // Shift+Ctrl+F10
    {"\x1b[23;6~", events.KeyboardEvent{Code: "F11", Ctrl: true, Shift: true}}, // Shift+Ctrl+F11
    {"\x1b[24;6~", events.KeyboardEvent{Code: "F12", Ctrl: true, Shift: true}}, // Shift+Ctrl+F12
    {"\x1b[5;6~", events.KeyboardEvent{Code: "PageUp", Ctrl: true, Shift: true}}, // Shift+Ctrl+PageUp
    {"\x1b[6;6~", events.KeyboardEvent{Code: "PageDown", Ctrl: true, Shift: true}}, // Shift+Ctrl+PageDown
    {"\x1b[1;6H", events.KeyboardEvent{Code: "Home", Ctrl: true, Shift: true}}, // Shift+Ctrl+Home
    {"\x1b[1;6F", events.KeyboardEvent{Code: "End", Ctrl: true, Shift: true}}, // Shift+Ctrl+End
    {"\x1b[2;6~", events.KeyboardEvent{Code: "Insert", Ctrl: true, Shift: true}}, // Shift+Ctrl+Insert
    {"\x1b[3;6~", events.KeyboardEvent{Code: "Delete", Ctrl: true, Shift: true}}, // Shift+Ctrl+Delete
    {"\x1b[1;6A", events.KeyboardEvent{Code: "Up", Ctrl: true, Shift: true}}, // Shift+Ctrl+Up
    {"\x1b[1;6B", events.KeyboardEvent{Code: "Down", Ctrl: true, Shift: true}}, // Shift+Ctrl+Down
    {"\x1b[1;6C", events.KeyboardEvent{Code: "Right", Ctrl: true, Shift: true}}, // Shift+Ctrl+Right
    {"\x1b[1;6D", events.KeyboardEvent{Code: "Left", Ctrl: true, Shift: true}}, // Shift+Ctrl+Left
    // Alt + Shift
    {"\x1b[;4P", events.KeyboardEvent{Code: "F1", Alt: true, Shift: true}}, // Shift+Alt+F1
    {"\x1b[;4Q", events.KeyboardEvent{Code: "F2", Alt: true, Shift: true}}, // Shift+Alt+F2
    {"\x1b[;4R", events.KeyboardEvent{Code: "F3", Alt: true, Shift: true}}, // Shift+Alt+F3
    {"\x1b[;4S", events.KeyboardEvent{Code: "F4", Alt: true, Shift: true}}, // Shift+Alt+F4
    {"\x1b[15;4~", events.KeyboardEvent{Code: "F5", Alt: true, Shift: true}}, // Shift+Alt+F5
    {"\x1b[17;4~", events.KeyboardEvent{Code: "F6", Alt: true, Shift: true}}, // Shift+Alt+F6
    {"\x1b[18;4~", events.KeyboardEvent{Code: "F7", Alt: true, Shift: true}}, // Shift+Alt+F7
    {"\x1b[19;4~", events.KeyboardEvent{Code: "F8", Alt: true, Shift: true}}, // Shift+Alt+F8
    {"\x1b[20;4~", events.KeyboardEvent{Code: "F9", Alt: true, Shift: true}}, // Shift+Alt+F9
    {"\x1b[21;4~", events.KeyboardEvent{Code: "F10", Alt: true, Shift: true}}, // Shift+Alt+F10
    {"\x1b[23;4~", events.KeyboardEvent{Code: "F11", Alt: true, Shift: true}}, // Shift+Alt+F11
    {"\x1b[24;4~", events.KeyboardEvent{Code: "F12", Alt: true, Shift: true}}, // Shift+Alt+F12
    {"\x1b[5;4~", events.KeyboardEvent{Code: "PageUp", Alt: true, Shift: true}}, // Shift+Alt+PageUp
    {"\x1b[6;4~", events.KeyboardEvent{Code: "PageDown", Alt: true, Shift: true}}, // Shift+Alt+PageDown
    {"\x1b[1;4H", events.KeyboardEvent{Code: "Home", Alt: true, Shift: true}}, // Shift+Alt+Home
    {"\x1b[1;4F", events.KeyboardEvent{Code: "End", Alt: true, Shift: true}}, // Shift+Alt+End
    {"\x1b[2;4~", events.KeyboardEvent{Code: "Insert", Alt: true, Shift: true}}, // Shift+Alt+Insert
    {"\x1b[3;4~", events.KeyboardEvent{Code: "Delete", Alt: true, Shift: true}}, // Shift+Alt+Delete
    {"\x1b[1;4A", events.KeyboardEvent{Code: "Up", Alt: true, Shift: true}}, // Shift+Alt+Up
    {"\x1b[1;4B", events.KeyboardEvent{Code: "Down", Alt: true, Shift: true}}, // Shift+Alt+Down
    {"\x1b[1;4C", events.KeyboardEvent{Code: "Right", Alt: true, Shift: true}}, // Shift+Alt+Right
    {"\x1b[1;4D", events.KeyboardEvent{Code: "Left", Alt: true, Shift: true}}, // Shift+Alt+Left
    // Ctrl + Alt + Shift
    {"\x1b[;8P", events.KeyboardEvent{Code: "F1", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F1
    {"\x1b[;8Q", events.KeyboardEvent{Code: "F2", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F2
    {"\x1b[;8R", events.KeyboardEvent{Code: "F3", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F3
    {"\x1b[;8S", events.KeyboardEvent{Code: "F4", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F4
    {"\x1b[15;8~", events.KeyboardEvent{Code: "F5", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F5
    {"\x1b[17;8~", events.KeyboardEvent{Code: "F6", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F6
    {"\x1b[18;8~", events.KeyboardEvent{Code: "F7", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F7
    {"\x1b[19;8~", events.KeyboardEvent{Code: "F8", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F8
    {"\x1b[20;8~", events.KeyboardEvent{Code: "F9", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F9
    {"\x1b[21;8~", events.KeyboardEvent{Code: "F10", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F10
    {"\x1b[23;8~", events.KeyboardEvent{Code: "F11", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F11
    {"\x1b[24;8~", events.KeyboardEvent{Code: "F12", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+F12
    {"\x1b[5;8~", events.KeyboardEvent{Code: "PageUp", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+PageUp
    {"\x1b[6;8~", events.KeyboardEvent{Code: "PageDown", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+PageDown
    {"\x1b[1;8H", events.KeyboardEvent{Code: "Home", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+Home
    {"\x1b[1;8F", events.KeyboardEvent{Code: "End", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+End
    {"\x1b[2;8~", events.KeyboardEvent{Code: "Insert", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+Insert
    {"\x1b[3;8~", events.KeyboardEvent{Code: "Delete", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+Delete
    {"\x1b[1;8A", events.KeyboardEvent{Code: "Up", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+Up
    {"\x1b[1;8B", events.KeyboardEvent{Code: "Down", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+Down
    {"\x1b[1;8C", events.KeyboardEvent{Code: "Right", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+Right
    {"\x1b[1;8D", events.KeyboardEvent{Code: "Left", Alt: true, Ctrl: true, Shift: true}}, // Shift+Ctrl+Alt+Left
    // Special Keys
    {"\x1b", events.KeyboardEvent{Code: "Escape"}}, // Escape
    {"\x1b ", events.KeyboardEvent{Code: "Space",Key: " ", Alt: true}}, // Alt+Space
    {" ", events.KeyboardEvent{Code: "Space",Key: " "}}, // Space
    {"\x00", events.KeyboardEvent{Code: "Space",Key: " ", Ctrl: true}}, // Ctrl+Space
    {"\x1b\x00", events.KeyboardEvent{Code: "Space",Key: " ", Alt: true, Ctrl: true}}, // Ctrl+Alt+Space
    {"\x1c", events.KeyboardEvent{Code: "\\", Ctrl: true}}, // Ctrl+\
    {"\x1d", events.KeyboardEvent{Code: "]", Ctrl: true}}, // Ctrl+]
    {"\t", events.KeyboardEvent{Code: "Tab"}}, // Tab
    {"\x1b[Z", events.KeyboardEvent{Code: "Tab", Shift: true}}, // Shift+Tab
    {"\u007f", events.KeyboardEvent{Code: "Backspace"}}, // Backspace
    {"\b", events.KeyboardEvent{Code: "Backspace", Ctrl: true}}, // Ctrl+Backspace
    {"\x1b\u007f", events.KeyboardEvent{Code: "Backspace", Alt: true}}, // Alt+Backspace
    {"\x1b\b", events.KeyboardEvent{Code: "Backspace", Alt: true, Ctrl: true}}, // Ctrl+Alt+Backspace
    {"\r", events.KeyboardEvent{Code: "Return"}}, // Return
    {"\n", events.KeyboardEvent{Code: "Return", Ctrl: true}}, // Ctrl+Return
}
