name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...        

    - name: Test
      run: go test ./...
    
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install the linter
      run: go get -u golang.org/x/lint/golint

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...        

    - name: ENV
      run: env
    - name: GOENV
      run: go env
    - name: Install Linter
      run: go get -u golang.org/x/lint/golint 
    - name: Linter
      run: /home/runner/go/bin/golint ./...
